m-UpdateRegexForUpgradeConfig
Robert-Frampton/liferay-theme-tasks pull request #4
Opened 2017-04-13 18:55 UTC by blzaugg

2017-04-13 19:05 UTC, Robert-Frampton commented
Hey @blzaugg looks like the tests are failing, can you take a look?

2017-04-13 19:06 UTC, Robert-Frampton commented
Looks the the tests are failing for #3 as well.

2017-04-21 16:29 UTC, Robert-Frampton commented
Just started reviewing :) <br><br>:octocat: *Sent from [GH](http://nodegh.io).*

2017-04-21 16:36 UTC, robframpton requested changes

2017-04-21 16:36 UTC, Robert-Frampton commented on test/tasks/upgrade/config.js
>  		assert.fileContentMatch(pluginPackagePropertiesPath, /7\.0\.0\+/);
Hey @blzaugg 

This assertion is failing, it's looking for `7_0_0` in the look and feel file.

```
<!DOCTYPE look-and-feel PUBLIC "-//Liferay//DTD Look and Feel 7.0.0//EN" "http://www.liferay.com/dtd/liferay-look-and-feel_7.0.0.dtd">
```

That's what the file's doctype is after the upgrade task is run.

2017-04-21 17:32 UTC, blzaugg commented on lib/upgrade/6.2/upgrade.js
>  					},
I see the issue. I replaced with `'$17.0.0$2'`. I'll fix it.

2017-04-21 17:34 UTC, blzaugg commented on lib/upgrade/6.2/upgrade.js
>  					},
TODO: Replace with `'$17_0_0$2'`

2017-04-21 22:01 UTC, blzaugg commented
https://github.com/Robert-Frampton/liferay-theme-tasks/pull/5

2017-04-21 22:01 UTC, closed without merging